#!/bin/sh
execute_line="is_fix_active=$(tc filter show dev $(nvram get wan0_ifname) prio 99) \n if [ -z "$is_fix_active" ]; then { sh ./jffs/scripts/add_upload_fix & }; fi"
sed -i -e "${execute_line}" /jffs/scripts/firewall-start
sed -i -e "${execute_line}" /jffs/scripts/service-event-end
